---
title: "Extraer coords de instituciones"
author: "Elena Quintero"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(here)
library(dplyr)
library(OpenStreetMap)
library(RJSONIO)
```


```{r}
member.table <- gsheet::gsheet2tbl("1tRlCcIxurHIDg-CCHsFFbkD3e4YkiDlA3PkFlTcBlk8") 

only_inst <- member.table |> 
  dplyr::distinct(Institución, Ciudad, País)

only_inst$inst <- gsub(" ", "+", only_inst$Institución)
only_inst$city <- gsub(" ", "+", only_inst$city)
only_inst$country <- gsub(" ", "+", only_inst$País)


df_members <- member.table |> 
  #distinct(Institución, Ciudad, País) |> 
  dplyr::mutate(inst = stringr::str_replace_all(Institución, " ", "+"),
         inst = stringr::str_replace_all(inst, "-", ""),
         inst = stringr::str_replace_all(inst, ",", ""),
         inst = stringr::str_replace_all(inst, "\n", "+")) |> 
  dplyr::mutate(city = stringr::str_replace_all(`Ciudad`, " ", "+"),
         city = stringr::str_replace_all(city, "-", ""),
         city = stringr::str_replace_all(city, ",", "")) |> 
  dplyr::mutate(country = stringr::str_replace_all(País, " ", "+"),
         country = stringr::str_replace_all(country, "-", ""),
         country = stringr::str_replace_all(country, ",", ""))
```


```{r}
# df_members <- data.frame(inst = c("CREAF",
#                                   "EBD",
#                                   "Estacion+Biologica+de+Doñana"),
#                          city = c("Barcelona",
#                                   "Sevilla",
#                                   "Sevilla"),
#                          country = c("Spain",
#                                   "Spain",
#                                   "Spain"))
```

```{r}
locate <- function(row) {
  # First URL including the 'inst' field
  url1 <- paste0(
    "http://nominatim.openstreetmap.org/search?street=", 
    row["inst"], 
    "&city=", 
    row["city"], 
    "&country=", 
    row["country"], 
    "&limit=9&format=json"
  )
  
  # Try the first API call
  resOSM <- tryCatch({
    fromJSON(url1)
  }, error = function(e) {
    list() # Return empty list on error
  })
  
  # If first search has results, return coordinates
  if (length(resOSM) > 0) {
    return(c(resOSM[[1]]$lon, resOSM[[1]]$lat))
  }
  
  # Secondary URL omitting the 'inst' field
  url2 <- paste0(
    "http://nominatim.openstreetmap.org/search?city=", 
    row["city"], 
    "&country=", 
    row["country"], 
    "&limit=9&format=json"
  )
  
  # Try the second API call
  resOSM2 <- tryCatch({
    fromJSON(url2)
  }, error = function(e) {
    list() # Return empty list on error
  })
  
  # If second search has results, return coordinates
  if (length(resOSM2) > 0) {
    return(c(resOSM2[[1]]$lon, resOSM2[[1]]$lat))
  }
  
  # If both searches fail, return NA
  return(rep(NA, 2))
}

# Apply the function row-wise
coords <- t(apply(df_members, 1, locate)) |> 
  as.data.frame()


```



