---
title: "seminario8"
editor: visual
---

## Seminario 8. Introducción al análisis espacial de patrones de puntos

- [Introducción al análisis espacial de patrones de puntos. ¿Qué hago con mis coordenadas espaciales?](https://www.youtube.com/watch?v=1ye4v3ugAfc) 

- Impartido por: Antonio Perea Martos, Estación Experimental del Zaidín 

- CSIC, Granada - Resumen: Hubbell et al. en el año 2001 postularon que "Cualquier mecanismo de coexistencia que esté operando en un bosque deja una huella espacial que puede ser detectada haciendo mapas individuales de las localizaciones". Estas huellas espaciales vienen determinadas por la posición (X e Y) de los sujetos de estudios, y aportan pistas sobre los mecanismos que podrían estar operando en el ensamblaje de comunidades. Para analizar este tipo de huellas se requiere del uso del "point pattern analysis", una herramienta muy versátil y aplicable prácticamente a cualquier campo de la ecología que trabaje con localizaciones (puntos). Por tanto, el uso de este tipo de herramienta aporta una perspectiva añadida a los análisis estadísticos convencionales, evaluando el efecto de la distancia y la densidad en los procesos de interés. En este escenario veremos algunos ejemplos sobre las posibles aplicaciones de esta metodología, a la vez que se atenderán dudas según vayan surgiendo. 

- Fecha: 24 Octubre 2022
